### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by infacq** [SocialiteProviders/Dropbox#1]
Hi

I want to implement this using newest Laravel 5.1. Perhaps on the official docs you can separate the docs by the Laravel's version. I also find it hard for me to understand the flow.

**Comment by DraperStudio** [comment]
The docs are the same for Laravel 5 and 5.1 and I haven't seen anyone that didn't understand the docs. What exactly don't you understand?

**Comment by infacq** [comment]
about the facade. It's not clearly stated

**Comment by DraperStudio** [comment]
For that stuff you should read the official Socialite docs since this isn't part of our packages.

**Comment by infacq** [comment]
Ok I just figure out. you just use the socialite provided by Laravel.
